baseURL = "http://freakingpenguin.com/"
languageCode = "en-us"
title = "Richard Sent"
theme = "hugo-flex"

[params]
    mainSections = ["posts"]
    intro = true
    headline = "I write some stuff."
    description = "Another tech blog for the pile."
    gitlab = "https://gitlab.com/RJSent"
    email = "richard@freakingpenguin.com"
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"
    color = "#800020"
    footer = true
    math = true
    css = [ "css/lists.css", "css/code_blocks.css", "css/figures.css",
    "css/tables.css", "css/scrollbar.css", ]
    width = "47rem"
    summaries = true


[permalinks]
    posts = "posts/:filename/"

# Disabled due to messing up prime notation in KaTeX
# See https://github.com/KaTeX/KaTeX/issues/967
[markup.goldmark.extensions]
    typographer = false

[markup.goldmark.renderer]
    unsafe = true

[markup.highlight]
    style = "dracula"

# Overwrite setting in themes/hugo-flex/config.yaml, post -> posts
# Need to copy all of these, otherwise nav bar will be missing entries
[[menu.nav]]
    name = "About"
    url = "about/"
    weight = 1
[[menu.nav]]
    name = "Posts"
    url = "posts/"
    weight = 2
[[menu.nav]]
    name = "Tags"
    url = "tags/"
    weight = 3
[[menu.nav]]
    name = "Categories"
    url = "categories/"
    weight = 4
[[menu.nav]]
    name = "RSS"
    url = "index.xml"
    weight = 5	