baseURL = "http://example.org/"
languageCode = "en-us"
title = "Freaking Penguin"
theme = "hugo-flex"

[Params]
    mainSections = ["posts"]
    intro = true
    headline = "My headline"
    description = "My description"
    gitlab = "https://gitlab.com/RJSent"
    email = "richard@freakingpenguin.com"
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"
    color = "#800020"
    footer = true

[Permalinks]
    posts = "posts/:filename/"

[markup.goldmark.renderer]
  unsafe = true

[[menu.nav]]
name = "About"
url = "about/"
weight = 1

# Overwrite setting in themes/hugo-flex/config.yaml, post -> posts
[[menu.nav]]
name = "Posts"
url = "posts/"
weight = 2

[[menu.nav]]
name = "Tags"
url = "tags/"
weight = 3

[[menu.nav]]
name = "Categories"
url = "categories/"
weight = 4

[[menu.nav]]
name = "RSS"
url = "index.xml"
weight = 5