#!/usr/bin/env sh
:; set -e # -*- mode: emacs-lisp; lexical-binding: t -*-
:; emacs --no-site-file --script "$0" -- "$@" || __EXITCODE=$?
:; exit ${__EXITCODE:-0}
;; This code was taken from michaeljherold.com/articles/using-ox-hugo-without-duplication/
(defvar bootstrap-version)
(defvar straight-base-dir)
;; (defvar straight-fix-org)
(defvar straight-vc-git-default-clone-depth 1)
(defvar publish--straight-repos-dir)
(defvar org-confirm-babel-evaluate)
(defvar ob-mermaid-cli-path)
(defvar richard-babel-languages-to-eval (list 'mermaid))

(setq gc-cons-threshold 83886080 ; 80MiB
      straight-base-dir (expand-file-name "../.." (or load-file-name buffer-file-name))
      ;; straight-fix-org t
      straight-vc-git-default-clone-depth 1
      publish--straight-repos-dir (expand-file-name "straight/repos/" straight-base-dir))

(let ((bootstrap-file (expand-file-name "straight/repos/straight.el/bootstrap.el" straight-base-dir))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
	(url-retrieve-synchronously
	 "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
	 'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(message "Downloading dependencies...")
;; ox-hugo clones org as dependency, redundant (also org != org-mode apparently??)
;; (straight-use-package
;;  '(org-mode :type git
;; 	    :host github
;; 	    :repo "emacs-straight/org-mode"
;; 	    :files ("*.el" "lisp/*.el" "contrib/lisp/*.el")))
(straight-use-package
 '(ox-hugo :type git
	   :host github
	   :repo "kaushalmodi/ox-hugo"
	   :nonrecursive t))
(straight-use-package
 '(ob-mermaid :type git
	      :host github
	      :repo "arnm/ob-mermaid"
	      :nonrecursive t))
;; TODO: Automate install of mermaid-cli, npm install
;; @mermaid-js/mermaid-cli, which requires install of npm
(setq ob-mermaid-cli-path "~/.node_modules/.bin/mmdc")

(with-current-buffer (find-file-noselect (expand-file-name "blog.org" "."))
  (org-next-visible-heading 1)

  (when (equal (org-entry-get (point) "CUSTOM_ID") "toc")
    (let ((inhibit-message t))
      (org-cut-subtree)))

  (message "Evaluating code blocks...")
  ;; Mermaid seems to generate graphs twice, once on
  ;; (org-babel-execute-buffer) and once on export.
  ;; Created band-aid fix by removing (org-babel-execute-buffer). Not
  ;; sure of cause.
  (defadvice org-babel-execute-src-block (around conditional-eval nil activate)
    "Execute src-block if the block's language is in richard-babel-languages-to-eval"
    (let ((language (org-element-property :language (org-element-at-point))))
      (if (member (intern language) richard-babel-languages-to-eval)
	  (progn (message language)
		 ad-do-it))))

  ;; TODO: Use richard-babel-languages-to-eval
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((mermaid . t)))

  (setq org-confirm-babel-evaluate nil)
  ;; For some reason advice causes the execute buffer to not be
  ;; needed as they are then properly evaled on export by hugo.
  ;; (org-babel-execute-buffer)

  (message "Publishing...")
  (org-hugo-export-wim-to-md t))
